// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace klasser_instanser
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for KlasserInstanserClient.
    /// </summary>
    public static partial class KlasserInstanserClientExtensions
    {
            /// <summary>
            /// Returns all pets from the system that the user has access to
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='tags'>
            /// tags to filter by
            /// </param>
            /// <param name='limit'>
            /// maximum number of results to return
            /// </param>
            public static IList<Pet> FindPets(this IKlasserInstanserClient operations, IList<string> tags = default(IList<string>), int? limit = default(int?))
            {
                return Task.Factory.StartNew(s => ((IKlasserInstanserClient)s).FindPetsAsync(tags, limit), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Returns all pets from the system that the user has access to
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='tags'>
            /// tags to filter by
            /// </param>
            /// <param name='limit'>
            /// maximum number of results to return
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<Pet>> FindPetsAsync(this IKlasserInstanserClient operations, IList<string> tags = default(IList<string>), int? limit = default(int?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.FindPetsWithHttpMessagesAsync(tags, limit, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Creates a new pet in the store.  Duplicates are allowed
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='pet'>
            /// Pet to add to the store
            /// </param>
            public static Pet AddPet(this IKlasserInstanserClient operations, NewPet pet)
            {
                return Task.Factory.StartNew(s => ((IKlasserInstanserClient)s).AddPetAsync(pet), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Creates a new pet in the store.  Duplicates are allowed
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='pet'>
            /// Pet to add to the store
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Pet> AddPetAsync(this IKlasserInstanserClient operations, NewPet pet, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.AddPetWithHttpMessagesAsync(pet, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Returns a user based on a single ID, if the user does not have access to
            /// the pet
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// ID of pet to fetch
            /// </param>
            public static Pet FindPetById(this IKlasserInstanserClient operations, long id)
            {
                return Task.Factory.StartNew(s => ((IKlasserInstanserClient)s).FindPetByIdAsync(id), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Returns a user based on a single ID, if the user does not have access to
            /// the pet
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// ID of pet to fetch
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Pet> FindPetByIdAsync(this IKlasserInstanserClient operations, long id, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.FindPetByIdWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// deletes a single pet based on the ID supplied
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// ID of pet to delete
            /// </param>
            public static void DeletePet(this IKlasserInstanserClient operations, long id)
            {
                Task.Factory.StartNew(s => ((IKlasserInstanserClient)s).DeletePetAsync(id), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// deletes a single pet based on the ID supplied
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// ID of pet to delete
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task DeletePetAsync(this IKlasserInstanserClient operations, long id, CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.DeletePetWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false);
            }

    }
}
